services:
  mongo:
    image: mongo:latest
    container_name: chatmu-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: ChatMu
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - chatmu-network

  mongo-express:
    image: mongo-express
    restart: always
    container_name: chatmu-mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://root:admin123@mongo:27017
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
    networks:
      - chatmu-network

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: chatmu-server
    restart: always
    ports:
      - 3003:3003
    environment:
      NODE_ENV: production
      PORT: 3003
      HOSTNAME: 0.0.0.0
    depends_on:
      - mongo
    networks:
      - chatmu-network
    volumes:
      - ./apps/server/src:/app/apps/server/src
      - /app/node_modules

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: chatmu-web
    restart: always
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_SOCKET_URL: http://localhost:3003
      MONGODB_URI: ${MONGODB_URI}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DB}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      RESEND_API_KEY: ${RESEND_API_KEY}
    depends_on:
      - server
      - mongo
    networks:
      - chatmu-network
    volumes:
      - ./apps/web/src:/app/apps/web/src
      - /app/node_modules
  # test:
  #   image: alpine
  #   env_file:
  #     - .env
  #     - .env.local
  #   command: sh -c "echo ENV_VALUE=${HELLO_WORLD}"
networks:
  chatmu-network:
    driver: bridge

volumes:
  mongo-data:
