services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: trah
      MONGO_INITDB_ROOT_PASSWORD: trah
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: trah
      ME_CONFIG_MONGODB_ADMINPASSWORD: trah
      ME_CONFIG_MONGODB_URL: mongodb://trah:trah@mongo:27017/
      ME_CONFIG_BASICAUTH: false
volumes:
  mongo-data:
