export const chatData = [
  {
    uriProfile: "/images/siprogrammer.jpg",
    user: "Fitrah",
    isRead: false,
    message: "lorem ipsum dolor sit amet",
    id: 1,
    date: "Hari ini",
    number: 1000,
  },
  {
    uriProfile: "/images/user2.jpg",
    user: "John Doe",
    isRead: true,
    message: "Hello, how are you?",
    id: 2,
    date: "Kemarin",
    number: 500,
  },
  {
    uriProfile: "/images/user3.jpg",
    user: "Jane Smith",
    isRead: false,
    message: "Can we meet tomorrow?",
    id: 3,
    date: "2 hari yang lalu",
    number: 200,
  },
  {
    uriProfile: "/images/user4.jpg",
    user: "Alice Johnson",
    isRead: true,
    message: "Sure, see you then!",
    id: 4,
    date: "3 hari yang lalu",
    number: 150,
  },
];
chatData.push(
  {
    uriProfile: "/images/user5.jpg",
    user: "Bob Brown",
    isRead: false,
    message: "What's the plan for today?",
    id: 5,
    date: "4 hari yang lalu",
    number: 120,
  },
  {
    uriProfile: "/images/user6.jpg",
    user: "Charlie Davis",
    isRead: true,
    message: "I'll be there in 10 minutes.",
    id: 6,
    date: "5 hari yang lalu",
    number: 300,
  },
  {
    uriProfile: "/images/user7.jpg",
    user: "Diana Evans",
    isRead: false,
    message: "Can you send me the report?",
    id: 7,
    date: "6 hari yang lalu",
    number: 250,
  },
  {
    uriProfile: "/images/user8.jpg",
    user: "Ethan Foster",
    isRead: true,
    message: "Meeting has been rescheduled.",
    id: 8,
    date: "Seminggu yang lalu",
    number: 400,
  },
  {
    uriProfile: "/images/user9.jpg",
    user: "Fiona Green",
    isRead: false,
    message: "Happy Birthday!",
    id: 9,
    date: "8 hari yang lalu",
    number: 600,
  },
  {
    uriProfile: "/images/user10.jpg",
    user: "George Harris",
    isRead: true,
    message: "Let's catch up soon.",
    id: 10,
    date: "9 hari yang lalu",
    number: 700,
  },
  {
    uriProfile: "/images/user11.jpg",
    user: "Hannah Irving",
    isRead: false,
    message: "Can you review this document?",
    id: 11,
    date: "10 hari yang lalu",
    number: 800,
  },
  {
    uriProfile: "/images/user12.jpg",
    user: "Ian Jackson",
    isRead: true,
    message: "I'll call you later.",
    id: 12,
    date: "11 hari yang lalu",
    number: 900,
  },
  {
    uriProfile: "/images/user13.jpg",
    user: "Jackie King",
    isRead: false,
    message: "Thank you for your help.",
    id: 13,
    date: "12 hari yang lalu",
    number: 100,
  },
  {
    uriProfile: "/images/user14.jpg",
    user: "Kevin Lee",
    isRead: true,
    message: "See you at the event.",
    id: 14,
    date: "13 hari yang lalu",
    number: 50,
  }
);
